include:
  - project: tmobile/templates
    ref: tmo/master
    file: /gitlab-ci/.tmo.global.common.gitlab-ci.yml

  - project: tmobile/conducktor/self-service/go-pipeline
    ref: tmo/master
    file: /gitlab-ci/.duck.semantic-release-main.gitlab-ci.yml

  - project: tmobile/conducktor/self-service/go-pipeline
    ref: tmo/master
    file: /gitlab-ci/.init-env.gitlab-ci.yml

  - project: tmobile/conducktor/self-service/go-pipeline
    ref: tmo/master
    file: /gitlab-ci/.docker-package.gitlab-ci.yml

  - project: tmobile/conducktor/self-service/go-pipeline
    ref: tmo/master
    file: /gitlab-ci/.deploy.gitlab-ci.yml

stages:
  - tmo
  - build-prep
  - test
  - build
  - package
  - release
  - deploy
  - triggers

variables:
  DOCKER_BUILD_ARGS: "--build-arg SSH_KEY=$SSH_PRIVATE_KEY_BASE64"
  GIT_DEPTH: 1

unit-test:
  stage: test
  image: $CI_REGISTRY/tmobile/conducktor/self-service/baseimages/duckwebbase:1.2.0
  script:
    - node --version
    - npm --version
    - apt-get install -yq git openssh-client
    - mkdir -p -m 0600 ~/.ssh && ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - ssh-agent sh -c 'echo $SSH_PRIVATE_KEY_BASE64 | base64 -d | ssh-add - ; npm install --unsafe-perm'
    - npm run test

version-setup:
  stage: build
  image: $CI_REGISTRY/tmobile/conducktor/self-service/baseimages/duckwebbase:1.2.0
  script:
    - node version-setup.js $RELEASE_VERSION 
  artifacts:
    paths:
    - ./public/
