apiVersion: skaffold/v1beta10
kind: Config
build:
  artifacts:
  - image: qlkube/qlkube
deploy:
  kubectl:
    manifests:
    - deployments/deployment.yaml
profiles:
  - name: travis-ci
    build:
      local:
        push: false
  - name: travis-release
    build:
      tagPolicy:
        envTemplate:
          template: '{{.IMAGE_NAME}}:{{.TRAVIS_TAG}}'